version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.Api
      target: deploy
    image: scb/task_application
    container_name: task_app
    links:
      - 'db'
    ports:
      - 3000:3000
    # command: node ./cmd/rest.cmd.js
    depends_on:
      - db
    restart: always
  db:
    build:
      context: .
      args:
        - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER:${MYSQL_USER}
        - MYSQL_PASSWORD:${MYSQL_PASSWORD}
        - MYSQL_DATABASE:${MYSQL_DATABASE}
      dockerfile: ./docker/Dockerfile.MySQL
    env_file:
      - .env
    image: scb/task_db
    container_name: task_db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
networks:
  database:
